<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pseudocode</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>pseudocode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(and|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|\=|\&lt;|\&gt;|≠)</string>
			<key>name</key>
			<string>keyword.operator.comparison.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(If|Case|Then|Else|Unless|Each|For|End|if|else|then|unless|each|for|end|case)\b</string>
			<key>name</key>
			<string>keyword.control.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Let|PatternCount|Left|Right)\b</string>
			<key>name</key>
			<string>support.function.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(script|code|realtime|offline):</string>
			<key>name</key>
			<string>entity.name.function.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z_]+:</string>
			<key>name</key>
			<string>constant.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b(?![?!])</string>
			<key>name</key>
			<string>constant.language.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\${0,2})[A-Z_]{2,}</string>
			<key>name</key>
			<string>variable.other.readwrite.instance.pseudocode</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>symbols</string>
			<key>match</key>
			<string>(?&lt;!:)(:)(?&gt;[a-zA-Z_]\w*(?&gt;[?!]|=(?![&gt;=]))?|===?|&gt;[&gt;=]?|&lt;[&lt;=]?|&lt;=&gt;|[%&amp;`/\|]|\*\*?|=?~|[-+]@?|\[\]=?|@@?[a-zA-Z_]\w*)</string>
			<key>name</key>
			<string>constant.other.symbol.pseudocode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z][a-z_]+[A-Z][a-z_]*\b</string>
			<key>name</key>
			<string>variable.other.constant.pseudocode</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.pseudocode</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^[ \t]+)?(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pseudocode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pseudocode</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pseudocode</string>
	<key>uuid</key>
	<string>1B48A3B6-D8C7-4F13-B75F-CCBC8D482580</string>
</dict>
</plist>
